---
abstract: 'A class based representation of an InterMine DB schema'
author:
  - 'Alex Kalderimis <dev@intermine.org>'
build_requires:
  Test::Exception: '0'
  Test::More: '0.95'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4216, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: InterMine-Model
provides:
  InterMine::Model:
    file: lib/InterMine/Model.pm
    version: '0.9903'
  InterMine::Model::Attribute:
    file: lib/InterMine/Model/Attribute.pm
    version: 0
  InterMine::Model::ClassDescriptor:
    file: lib/InterMine/Model/ClassDescriptor.pm
    version: 0
  InterMine::Model::Collection:
    file: lib/InterMine/Model/Collection.pm
    version: 0
  InterMine::Model::Handler:
    file: lib/InterMine/Model/Handler.pm
    version: 0
  InterMine::Model::Object:
    file: lib/InterMine/Model/Object.pm
    version: 0
  InterMine::Model::Reference:
    file: lib/InterMine/Model/Reference.pm
    version: 0
  InterMine::Model::Role::Descriptor:
    file: lib/InterMine/Model/Role/Descriptor.pm
    version: 0
  InterMine::Model::Role::Field:
    file: lib/InterMine/Model/Role/Field.pm
    version: 0
  InterMine::Model::TestModel:
    file: lib/InterMine/Model/TestModel.pm
    version: 0
  InterMine::Model::Types:
    file: lib/InterMine/Model/Types.pm
    version: 0
requires:
  Carp: '0'
  Moose: '2'
  Moose::Util::TypeConstraints: '2'
  MooseX::Role::WithOverloading: '0.09'
  MooseX::Types: '0'
  Scalar::Util: '0'
  Time::HiRes: '0'
  XML::Parser::Expat: '0'
  XML::Parser::PerlSAX: '0.08'
  perl: v5.8.3
resources:
  license: http://dev.perl.org/licenses/
version: '0.9904'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
